# =====================================================================
# Training configuration
# =====================================================================


# ---------------------------------------------------------------------
# Dataset paths
# ---------------------------------------------------------------------

# Expected structure:
#
# TRAIN_ROOT/
#     spline/
#         X0053_Y0049/*.npz
#     S1/
#         X0053_Y0049/*.npz
#     dsm/
#         X0053_Y0049/*.npz
#
# VAL_ROOT/
#     spline/
#     S1/
#     dsm/

TRAIN_ROOT = ("/data/ahsoka/eocp/wengler/height_database/DE_chips/train")

VAL_ROOT = ("/data/ahsoka/eocp/wengler/height_database/DE_chips/val")


# ---------------------------------------------------------------------
# Input channels
# ---------------------------------------------------------------------

# Number of Sentinel-2 spline coefficient channels.
NUM_BANDS = 220

# Add VH - VV as a third Sentinel-1 channel.
ADD_S1_RATIO = True

# Must correspond to ADD_S1_RATIO:
#
# False -> 2 channels: VH, VV
# True  -> 3 channels: VH, VV, VH - VV
S1_BANDS = 3


# ---------------------------------------------------------------------
# Sentinel-1 preprocessing
# ---------------------------------------------------------------------

# Nodata value stored in the prechipped S1 arrays.
S1_NODATA = -9999

# Use 100.0 only when S1 values are stored as scaled dB:
#
# -2000 -> -20 dB
# -1000 -> -10 dB
#
# Set to None if the NPZ arrays already contain actual dB values.
S1_SCALE_FACTOR = 100.0


# ---------------------------------------------------------------------
# Training settings
# ---------------------------------------------------------------------

BATCH_SIZE = 12
ACCUM_STEPS = 1

EPOCHS = 100
LEARNING_RATE = 1e-4

DEVICE = "cuda"

NUM_WORKERS = 2
NUM_THREADS = 8

EXCLUDED_YEARS = (2022,)

TRAIN_CHIPS_PER_EPOCH = 8004
VALIDATION_CHIPS = 2000
VALIDATION_SEED = 42


# ---------------------------------------------------------------------
# Output and logging
# ---------------------------------------------------------------------

RUN_NAME = "DE_Firsttest_22072026"

MODEL_OUT = (
    "/data/ahsoka/eocp/wengler/height_database/DE_out/DE_model/models/"
    f"{RUN_NAME}.pth"
)

LOG_PATH = (
    "/data/ahsoka/eocp/wengler/height_database/DE_out/DE_model/log/"
    f"{RUN_NAME}.log"
)

TB_LOG_DIR = (
    "/data/ahsoka/eocp/wengler/height_database/DE_out/DE_model/TB/"
    f"{RUN_NAME}"
)



# ---------------------------------------------------------------------
# Prediction inputs
# ---------------------------------------------------------------------

PREDICTION_SPLINE_ROOT = (
    "/data/ahsoka/eocp/forestpulse/"
    "01_data/02_processed_data/ThermSpline_DC"
)

PREDICTION_S1_ROOT = (
    "/data/ahsoka/eocp/wengler/"
    "height_database/composite/S1/DE"
)

PREDICTION_TILE_LIST_FILE = "/data/ahsoka/eocp/wengler/height_database/DE_out/Tile_allow_ger.txt"

PREDICTION_YEARS = [2020]


# ---------------------------------------------------------------------
# Prediction processing
# ---------------------------------------------------------------------

PREDICTION_PATCH_SIZE = 256
PREDICTION_BATCH_SIZE = 28
PREDICTION_TILE_SIZE = 1536



# ---------------------------------------------------------------------
# Prediction outputs
# ---------------------------------------------------------------------

PREDICTION_OUTPUT_ROOT = "/data/ahsoka/eocp/wengler/height_database/DE_out/DE_model/prediction/DE_Firsttest_22072026_211cm"

# By default, predict using the model generated by this training run.
PREDICTION_MODEL = "/data/ahsoka/eocp/wengler/height_database/DE_out/DE_model/models/DE_Firsttest_22072026_211cm.pth"